coverage:
  precision: 2           # how many decimal places to display in the UI: 0 <= value <= 4
  round: down            # how coverage is rounded: down/up/nearest
  range: "70...100"      # custom range of coverage colors from red -> yellow -> green

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: auto            # specify the target coverage for each commit status
        threshold: 1%          # allowed to drop X% and still result in a "success" commit status

ignore:
  - "internal/pkg/dpluger"