queue_rules:
  - name: default
    conditions:
      - status-success=build-test
  - name: maintainer-1
    conditions:
        - status-success=build-test
  - name: maintainer-2
    conditions:
        - status-success=build-test
  - name: maintainer-3
    conditions:
        - status-success=build=test
  
  - name: automatic
    conditions:
      - status-success=build-test
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
    
pull_request_rules:
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: true

  - name: automatic merge for maintainer 1
    conditions:
      - author=mmta
      - base=master
    actions:
      queue:
        method: squash
        name: maintainer-1

  - name: automatic merge for maintainer 2
    conditions:
      - author=Cempakers87
      - base=master
    actions:
      queue:
        method: squash
        name: maintainer-2

  - name: automatic merge for maintainer 3
    conditions:
      - author=rkspx
      - base=master
    actions:
      queue:
        method: squash
        name: maintainer-3

  - name: automatic merge on CI success and review
    conditions:
      - base=master
    actions:
      queue:
        method: squash
        name: automatic

  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
