pull_request_rules:
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: true
  - name: automatic merge for maintainer 1
    conditions:
      - author=mmta
      - status-success=build-test
      - base=master
    actions:
      merge:
        method: squash
        strict: smart
  - name: automatic merge for maintainer 2
    conditions:
      - author=Cempakers87
      - status-success=build-test
      - base=master
    actions:
      merge:
        method: squash
        strict: smart
    actions:
      merge:
        method: merge
        strict: smart
  - name: automatic merge on CI success and review
    conditions:
      - status-success=build-test
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#commented-reviews-by=0"
      - "approved-reviews-by=[mmta,Cempakers87]"
      - base=master
    actions:
      merge:
        method: squash
        strict: smart
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
