version: "3"
services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    deploy:
      replicas: 1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 9200:9200
    networks:
      - siemnet
    volumes:
      - es-data:/usr/share/elasticsearch/data

  logstash:
    container_name: logstash
    image: defenxor/docker-logstash:6.4.2
    command:
      - -f/etc/logstash/conf.d
    deploy:
      replicas: 1
    environment:
      - xpack.monitoring.enabled=false
    networks:
      - siemnet
    volumes:
      - ./conf/logstash/conf.d:/etc/logstash/conf.d
      - ./conf/logstash/index-template.d:/etc/logstash/index-template.d

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:6.4.2
    deploy:
      replicas: 1
    environment:
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5601:5601      
    networks:
      - siemnet

  dsiem:
    container_name: dsiem
    image: defenxor/dsiem:latest
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    networks:
      - siemnet
    volumes:
      - dsiem-log:/dsiem/logs

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:6.4.2
    user: root
    deploy:
      replicas: 1
    networks:
      - siemnet
    volumes:
      - dsiem-log:/var/log/dsiem
      - filebeat-data:/usr/share/filebeat/data
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml

volumes:
  dsiem-log:
  filebeat-data:
  es-data:
networks:
  siemnet: