// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package dsiem

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("filebeat", "dsiem", asset.ModuleFieldsPri, AssetDsiem); err != nil {
		panic(err)
	}
}

// AssetDsiem returns asset data.
// This is the base64 encoded gzipped contents of module/dsiem.
func AssetDsiem() string {
	return "eJx8j00OgyAQhfec4sW9F2DRGzTpDQzpTM1EEAKY1ts3am39IWXH+/nypkbHowYlYaeALNmyRjX/KwUQp3uUkMX3GhcFYMni6mmwrICHsKWkZ6tGbxz/cNPLY2CNNvohfJQCc4/Zoow10X3VQ3mZcozwy7gwnXGzbBLDEK3aJnXeVZpxmtII7cwV1PH49HHrFRlRUlfsW9+36m91CGQyU5PFcREx2WeEegcAAP//pe56wQ=="
}
